Pre diego pull-in

diff --git a/packages/cell-helpers/packaging b/packages/cell-helpers/packaging
--- a/packages/cell-helpers/packaging
+++ b/packages/cell-helpers/packaging
@@ -1,8 +1,12 @@
-set -e -x
+set -e
+
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
 
 export GOROOT=$(readlink -nf /var/vcap/packages/golang1.4)
 export PATH=$GOROOT/bin:$PATH
-export GOPATH=$PWD/lattice/cell-helpers
+go install lattice/cell-helpers/tee2metron
 
-go install tee2metron
-cp -a $PWD/lattice/cell-helpers/bin/tee2metron ${BOSH_INSTALL_TARGET}
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
